proiect/companies/urls.py
from django.urls import path
from companies import views

app_name = 'companies'

urlpatterns = [
    path('adaugare/', views.CreateCompaniesView.as_view(), name='adaugare_companie'),
    path('', views.CompaniesView.as_view(), name='lista_companii'),
]

proiect/locations/urls.py
from django.urls import path
from locations import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/modificare/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/dezactiveaza/', views.deactivate_location, name='dezactiveaza'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

proiect/my_api/urls.py
from rest_framework import routers
from django.urls import path, include
from my_api import views

router = routers.DefaultRouter()
router.register('api', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('locations.urls')),
    path('companies/', include('companies.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(), name='login'),
    path('userprofile/', include('userprofile.urls')),
    path('api/', include('my_api.urls')),
]

proiect/userprofile/urls.py
from django.urls import path
from userprofile import views

app_name = 'userprofile'
urlpatterns = [
    path('start_timesheet/', views.new_timesheet, name='start_pontaj'),
    path('stop_timesheet/', views.stop_timesheet, name='oprire_pontaj'),
    path('listare_utilizatori/', views.UserListView.as_view(), name='lista_utilizatori'),
    path('adauga_utilizator/', views.CreateNewAccount.as_view(), name='utilizator_nou'),
    path('<int:pk>/invite/', views.invita_utilizatorul, name='invitatie_utilizator'),
]

proiect/templates/base.html
<html>
<head>
    <title>Project Django</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <nav>

                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    {% if request.user.is_authenticated %}
                        <button type="submit">Logout</button>
                        <a class="btn" href="{% url 'locations:lista_locatii' %}">Location</a>
                        <a class="btn" href="{% url 'companies:lista_companii' %}">Companies</a>
                        <span style="font-weight: bold">Utilizator: {{ request.user.username }}</span>
                        {% if ready_to_work is False %}
                            <a href="{% url 'userprofile:oprire_pontaj' %}" class="btn btn-danger">Oprire pontaj</a>
                        {% else %}
                            <a href="{% url 'userprofile:start_pontaj' %}" class="btn btn-success">Pornire pontaj</a>
                        {% endif %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'userprofile:lista_utilizatori' %}" class="btn">Utilizatori</a>
                        {% endif %}
                    {% endif %}
                    <a class="btn" href="/admin/">Admin</a>
                </form>


            </nav>
        </div>
    </div>
</div>
{% block content %}
{% endblock %}
</body>
</html>

proiect/templates/forms.html
{% extends 'base.html' %}
{% block content %}
    <div class="col-md-12">
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <div class="col-md-6">
            {{ field.label }} {{ field }}
                <span style="color: red;">{{ field.errors }}</span>
            </div>
        {% endfor %}
    <button type="submit" class="btn btn-success">Salveaza</button>
    {% if 'adaugare' in request.path %}
        <a class="btn btn-info" href="{% url 'locations:lista_locatii' %}">Back</a>
    {% endif %}
    </form>
    </div>
{% endblock %}