proiect/locations/urls.py
from django.urls import path
from locations import views

app_name = 'locations'

urlpatterns = [
    path('', views.LocationView.as_view(), name='lista_locatii'),
    path('adaugare/', views.CreateLocationView.as_view(), name='adaugare'),
    path('<int:pk>/modificare/', views.UpdateLocationView.as_view(), name='modifica'),
    path('<int:pk>/dezactiveaza/', views.deactivate_location, name='dezactiveaza'),
    path('<int:pk>/activeaza/', views.activate_location, name='activeaza'),
]

proiect/my_api/urls.py
from rest_framework import routers
from django.urls import path, include
from my_api import views

router = routers.DefaultRouter()
router.register('api', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('locations.urls')),
    path('companies/', include('companies.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(), name='login'),
    path('userprofile/', include('userprofile.urls')),
    path('api/', include('my_api.urls')),
]

proiect/locations/models.py
from django.db import models


class Location(models.Model):

    city = models.CharField(max_length=100)
    country = models.CharField(max_length=100)
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)

    def __str__(self):
        return f"{self.city} - {self.country}"

proiect/locations/forms.py
from django import forms
from django.forms import TextInput

from locations.models import Location


class LocationsForm(forms.ModelForm):

    class Meta:
        model = Location
        fields = ['city', 'country']

        widgets = {
            'city': TextInput(attrs={'class': 'form-control', 'placeholder': 'city'}),
            'country': TextInput(attrs={'class': 'form-control', 'placeholder': 'country'})
        }

    def __init__(self, pk, *args, **kwargs):
        super(LocationsForm, self).__init__(*args, **kwargs)
        self.pk = pk

    def clean(self):
        city_value = self.cleaned_data.get('city')
        country_value = self.cleaned_data.get('country')
        if self.pk:
            if Location.objects.filter(city=city_value,
                                       country=country_value).exclude(id=self.pk).exists():
                self._errors['city'] = self.error_class(['Orasul si tara deja exista'])
        else:
            if Location.objects.filter(city=city_value, country=country_value).exists():
                self._errors['city'] = self.error_class(['Orasul si tara deja exista'])
        return self.cleaned_data

proiect/locations/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from locations.forms import LocationsForm
from locations.models import Location


class CreateLocationView(LoginRequiredMixin, CreateView):
    model = Location
    template_name = 'forms.html'
    # fields = ["city", "country"]
    form_class = LocationsForm

    def get_form_kwargs(self):
        data = super(CreateLocationView, self).get_form_kwargs()
        data.update({'pk': None})
        return data

    def get_success_url(self):
        return reverse('locations:lista_locatii')


class LocationView(LoginRequiredMixin, ListView):
    model = Location
    template_name = 'locations/location_index.html'


class UpdateLocationView(LoginRequiredMixin, UpdateView):
    model = Location
    # fields = ['city', 'country']
    form_class = LocationsForm
    template_name = 'forms.html'

    def get_form_kwargs(self):
        data = super(UpdateLocationView, self).get_form_kwargs()
        data.update({'pk': self.kwargs['pk']})
        return data

    def get_success_url(self):
        return reverse('locations:lista_locatii')


@login_required
def deactivate_location(request, pk):
    Location.objects.filter(id=pk).update(active=False)
    return redirect('locations:lista_locatii')


@login_required
def activate_location(request, pk):
    Location.objects.filter(id=pk).update(active=True)
    return redirect('locations:lista_locatii')

proiect/templates/locations/location_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'locations:adaugare' %}">Adaugare locatii</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>City</th>
                <th>Country</th>
                <th>State</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in location_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.city }}</td>
                    <td>{{ item.country }}</td>
                    <td>{% if item.active is True %}
                        Active
                        {% else %}
                        Inactiv
                        {% endif %}
                    <td>
                        <a class="btn btn-success" href="{% url 'locations:modifica' item.id %}">Editare</a>
                        {% if item.active is True %}
                        <a class="btn btn-danger" href="{% url 'locations:dezactiveaza' item.id %}">Dezactiveaza</a>
                        {% else %}
                        <a class="btn btn-warning" href="{% url 'locations:activeaza' item.id %}">Activeaza</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}