proiect/companies/urls.py
from django.urls import path
from companies import views

app_name = 'companies'

urlpatterns = [
    path('adaugare/', views.CreateCompaniesView.as_view(), name='adaugare_companie'),
    path('', views.CompaniesView.as_view(), name='lista_companii'),
]

proiect/my_api/urls.py
from rest_framework import routers
from django.urls import path, include
from my_api import views

router = routers.DefaultRouter()
router.register('api', views.LocationViewSet)

urlpatterns = [
    path('', include(router.urls))
]

proiect/proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('locations/', include('locations.urls')),
    path('companies/', include('companies.urls')),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(), name='login'),
    path('userprofile/', include('userprofile.urls')),
    path('api/', include('my_api.urls')),
]

proiect/companies/models.py
from django.db import models
from locations.models import Location


class Company(models.Model):
    company_choices = (('SRL', 'S.R.L'),
                       ('SA', 'S.A'))

    name = models.CharField(max_length=100)
    website = models.CharField(max_length=100)
    company_type = models.CharField(max_length=100, choices=company_choices)
    locations = models.ForeignKey(Location, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.company_type} {self.name}"

proiect/companies/forms.py
from django import forms
from django.forms import TextInput, ChoiceField, ModelChoiceField, Select

from companies.models import Company
from locations.models import Location


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

        widgets = {
            'name': TextInput(attrs={'placeholder': 'name', 'class': 'form-control'}),
            'website': TextInput(attrs={'placeholder': 'website', 'class': 'form-control'}),
            'company_type': Select(attrs={'class': 'form-control'}),
            'locations': Select(attrs={'class': 'form-control'})
        }

proiect/companies/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, ListView

from companies.forms import CompanyForm
from companies.models import Company


class CreateCompaniesView(LoginRequiredMixin, CreateView):
    model = Company
    form_class = CompanyForm
    template_name = 'forms.html'

    def get_success_url(self):
        return reverse('companies:lista_companii')


class CompaniesView(LoginRequiredMixin, ListView):
    model = Company
    template_name = 'companies/companies_index.html'

proiect/templates/companies/companies_index.html
{% extends 'base.html' %}
{% block content %}
    <a class="btn btn-primary" href="{% url 'companies:adaugare_companie' %}">Adaugare companie</a>
    <table class="table">
        <thead>
            <tr>
                <th>Index</th>
                <th>Name</th>
                <th>Website</th>
                <th>Company type</th>
                <th>Location</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for item in company_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ item.name }}</td>
                    <td>{{ item.website }}</td>
                    <td>{{ item.company_type }}</td>
                    <td>{{ item.locations }}</td>
                    <td>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}